### ISSUE TITLE
Selector library problem

### ISSUE THREAD

**Issue by muhammetfaik** [asterisk/ari-py#35]
I run `python playback_example.py` but I have this error:
```
Traceback (most recent call last):
  File "playback_example.py", line 13, in <module>
    import ari
  File "build/bdist.linux-x86_64/egg/ari/__init__.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/ari/client.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/swaggerpy/__init__.py", line 13, in <module>
  File "build/bdist.linux-x86_64/egg/swaggerpy/swagger_model.py", line 13, in <module>
  File "build/bdist.linux-x86_64/egg/swaggerpy/http_client.py", line 14, in <module>
  File "/usr/local/lib/python2.7/dist-packages/websocket_client-1.2.3-py2.7.egg/websocket/__init__.py", line 20, in <module>
    from ._app import WebSocketApp
  File "/usr/local/lib/python2.7/dist-packages/websocket_client-1.2.3-py2.7.egg/websocket/_app.py", line 23, in <module>
    import selectors
ImportError: No module named selectors
```
What is problem ?

**Comment by Yagna24** [comment]
You're running this on python 2.7. 

Python 3 has the selectors module, which allows us to register on a file descriptor event, and only later in a different part of the code select on it. In Python 2 we only have the select module, which requires that we 'register' and 'select' on the same line, which is limiting.

Run on python 3.0+
